### ISSUE TITLE
Shopify schema

### ISSUE THREAD

**Issue by firdausmaarof** [Shopify/graphql-ruby-client#19]
Where can i get the schema for shopify api? i cannot find enough documentation regarding this.

**Comment by theterminalguy** [comment]
@firdausmaarof take a look at this https://github.com/Shopify/graphql-js-client/blob/master/schema.json

**Comment by swalkinshaw** [comment]
You can get the schema by doing a standard GraphQL introspection query to our API endpoint once you're authenticated.

See https://help.shopify.com/en/api/graphql-admin-api/getting-started
